services:
    - xvfb
language: python
python:
    - 3.7
install:
    - pip install codecov
script:
    - python -m unittest discover tests
    - coverage run -m unittest discover tests
after_success:
    - codecov
